### ISSUE TITLE
swipe on mobile devices

### ISSUE THREAD

**Issue by onlinebizsoft** [tannerhodges/snap-slider#19]
Normally on mobile (or even desktop), we can touch and swipe the slide but with snap slider if we hide the scrollbar then look like we can't touch to scroll anymore.
Maybe it is something we need to implement with Javascript? It would be great because in fact, we always have to hide the scrollbar while we still need the touch functionality @tannerhodges

**Comment by tannerhodges** [comment]
❓ How are you hiding the scrollbar? / Could you share a demo or sample code I could look at?

I'll need to document it, but here's a class I've used to hide scrollbars on different projects:

```css
/**
 * Hide scrollbars in all major browsers.
 * @see https://stackoverflow.com/a/38994837
 */
/* Chrome/Safari */
.hide-scrollbars::-webkit-scrollbar { width: 0; }
/* Firefox */
.hide-scrollbars { scrollbar-width: none; }
```

You can either add that class to your slider HTML, or copy the CSS into your main slider class.

Let me know whether this helps. I'll share a demo below…

## 🙈 “Hide Scrollbars” Demo

https://codepen.io/tannerhodges/pen/vYJKVjK

https://user-images.githubusercontent.com/1619485/138009865-3c1a3660-f315-44e6-a309-e2bca7870587.mp4
